export const products = [
    {
        id:1,
        name:"Pulp fiction",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2017/07/Pulpfiction-510x744.jpg",
        stock:7,
        sizes:["30x45"],
        category:"cine y series",
    },
    {
        id:2,
        name:"Kill Bill",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2019/09/kill-bill-510x765.jpg",
        stock:7,
        sizes:["30x45"],
        category:"cine y series",
    },
    {
        id:3,
        name:"John Lennon Pop",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2022/07/john-lennon-pop-510x680.jpg",
        stock:7,
        sizes:["30x40"],
        category:"musica",
    },
    {
        id:4,
        name:"Star Wars Episode IV Chinese Version",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2019/11/star-wars-japones-Ajustado-low-510x778.jpg",
        stock:7,
        sizes:["30x45"],
        category:"cine y series",
    },
    {
        id:5,
        name:"Carlos Monzón",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2020/11/CArlos-Monzon-low-60-x-80-510x680.jpg",
        stock:7,
        sizes:["30x45"],
        category:"deportes",
    },
    {
        id:6,
        name:"GNR New York",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2017/10/GNR-new-york.jpg",
        stock:7,
        sizes:["30x45"],
        category:"musica",
    },
    {
        id:7,
        name:"Stranger Things Season 3",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2019/07/strangerthings_s3-low-60-x-90-510x756.jpg",
        stock:7,
        sizes:["30x45"],
        category:"cine y series",
    },
    {
        id:8,
        name:"Back To The Future",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2017/07/Back-To-The-Future-510x727.jpg",
        stock:7,
        sizes:["30x45"],
        category:"cine y series",
    },
    {
        id:9,
        name:"Muhammad Alí 1972",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2021/01/Muhammad-Ali-60-x-90-low-510x765.jpg",
        stock:7,
        sizes:["30x45"],
        category:"deportes",
    },
    {
        id:10,
        name:"Scarface Al Pacino",
        price:6000,
        description:"",
        image:"https://postercity.com.ar/wp-content/uploads/2019/07/Scarface-Al-Pacino-60-x-90-low-510x766.jpg",
        stock:7,
        sizes:["30x45"],
        category:"cine y series",
    },
]